### ISSUE TITLE
Gene Coverage display error

### ISSUE THREAD

**Issue by j-berg** [XPRESSyourself/XPRESSpipe#22]
```
Running complexity analysis of sequence libraries...
G17189.TCGA-06-0132-01A-02R-1849-01.2.bam_1_dedupMarked.bam has been processed.
Processing of batch 1 of 12 complete...
G17190.TCGA-06-0174-01A-01R-1849-01.2.bam_1_dedupMarked.bam has been processed.
Processing of batch 2 of 12 complete...
G17193.TCGA-06-0743-01A-01R-1849-01.2.bam_1_dedupMarked.bam has been processed.
Processing of batch 3 of 12 complete...
G17195.TCGA-06-0138-01A-02R-1849-01.2.bam_1_dedupMarked.bam has been processed.
Processing of batch 4 of 12 complete...
G17197.TCGA-06-0211-01B-01R-1849-01.2.bam_1_dedupMarked.bam has been processed.
Processing of batch 5 of 12 complete...
G17199.TCGA-06-0744-01A-01R-1849-01.2.bam_1_dedupMarked.bam has been processed.
Processing of batch 6 of 12 complete...
G17202.TCGA-06-0184-01A-01R-1849-01.2.bam_1_dedupMarked.bam has been processed.
Processing of batch 7 of 12 complete...
G17203.TCGA-06-0211-02A-02R-2005-01.2.bam_1_dedupMarked.bam has been processed.
Processing of batch 8 of 12 complete...
G17204.TCGA-08-0386-01A-01R-1849-01.2.bam_1_dedupMarked.bam has been processed.
Processing of batch 9 of 12 complete...
G17205.TCGA-06-0745-01A-01R-1849-01.2.bam_1_dedupMarked.bam has been processed.
Processing of batch 10 of 12 complete...
G17206.TCGA-06-0125-02A-11R-2005-01.2.bam_1_dedupMarked.bam has been processed.
Processing of batch 11 of 12 complete...
G17207.TCGA-06-0156-01A-03R-1849-01.2.bam_1_dedupMarked.bam has been processed.
Processing of batch 12 of 12 complete...
Traceback (most recent call last):
  File "/software/pkg/miniconda3/bin/xpresspipe", line 11, in <module>
    load_entry_point('XPRESSpipe', 'console_scripts', 'xpresspipe')()
  File "/XPRESSpipe/xpresspipe/__main__.py", line 617, in main
    make_complexity(args_dict)
  File "/XPRESSpipe/xpresspipe/complexity.py", line 107, in make_complexity
    args_dict['complexity'])
  File "/XPRESSpipe/xpresspipe/compile.py", line 273, in compile_complexity_metrics
    subplot_kw = {'facecolor':'none'})
  File "/software/pkg/miniconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 1184, in subplots
    fig = figure(**fig_kw)
  File "/software/pkg/miniconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/software/pkg/miniconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/software/pkg/miniconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 167, in new_figure_manager
    canvas = cls.FigureCanvas(figure)
  File "/software/pkg/miniconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 24, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/software/pkg/miniconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 234, in __init__
    _create_qApp()
  File "/software/pkg/miniconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 125, in _create_qAp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
```

**Comment by j-berg** [comment]
Appears to be fixed by 6b14d8586d5f0976e620a59f4a24ebfc9c763964. Now calls conditional switch of backend if not using `'agg'`
