### ISSUE TITLE
P-site QC not processing

### ISSUE THREAD

**Issue by j-berg** [XPRESSyourself/XPRESSpipe#36]
**Describe the bug**
Pipeline gets stuck on p-site QC. These seems to be a recurrent issue where the pipeline runs into issues with running riboWaltz consistently. Will try to get to the issue this weekend.

**To Reproduce**
1. Run general riboseq pipeline

**Screenshots**
```
Generating P-site meta profiles...
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/$USER/miniconda3/bin/xpresspipe", line 11, in <module>
    load_entry_point('XPRESSpipe', 'console_scripts', 'xpresspipe')()
  File "/uufs/chpc.utah.edu/common/home/$USER/XPRESSpipe/xpresspipe/__main__.py", line 734, in main
    make_periodicity(args_dict)
  File "/uufs/chpc.utah.edu/common/home/$USER/XPRESSpipe/xpresspipe/periodicity.py", line 149, in make_periodicity
    index_col=0)
  File "/uufs/chpc.utah.edu/common/home/$USER/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/uufs/chpc.utah.edu/common/home/$USER/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/uufs/chpc.utah.edu/common/home/$USER/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/uufs/chpc.utah.edu/common/home/$USER/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/uufs/chpc.utah.edu/common/home/$USER/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'/scratch/general/lustre/$USER/7794015/output/p_site_qc/metrics/annotation.txt' does not exist: b'/scratch/general/lustre/$USER/7794015/output/p_site_qc/metrics/annotation.txt'
```

**Desktop (please complete the following information):**
 - CHPC

**Additional context**

**Comment by j-berg** [comment]
Works perfectly fine with R 3.5.1, doesn't like 3.6. May need to restrict R version allowed on install

**Comment by j-berg** [comment]
For whatever reason, it does not like having all row subplots filled for the periodicity graphs. Currently adding a filler row which seems to keep it happy for now. Will need to look into this further at a later time to get past this issue. Seems to not be an issue for single-column multi-row plots. See 5751fc6 for fixes.
