### ISSUE TITLE
Failure to import xpressplot into python3

### ISSUE THREAD

**Issue by arish-n-shah** [XPRESSyourself/XPRESSpipe#47]
I am having issues getting xpressplot to import into python3. I hope I am forgetting something simple rather than this being an issue with the new M1 Macbook (which is what I am using). MacOS Big Sur v11.2, Chip - Apple M1, XPRESSpipe-v0.6.2

I have installed python 3.9.2
```
arish@dhcp-10-29-251-173 ~ % python --version
Python 3.9.2
```

I have already pip installed xpressplot using python3
```
arish@dhcp-10-29-251-173 ~ % python -m pip install xpressplot
Requirement already satisfied: xpressplot in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (0.2.5)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from xpressplot) (1.2.2)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from xpressplot) (1.20.1)
Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from xpressplot) (1.6.1)
Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from xpressplot) (0.24.1)
Requirement already satisfied: matplotlib<3.0.0,>=2.1.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from xpressplot) (2.2.5)
Requirement already satisfied: seaborn in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from xpressplot) (0.11.1)
Requirement already satisfied: plotly in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from xpressplot) (4.14.3)
Requirement already satisfied: plotly_express in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from xpressplot) (0.4.1)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from matplotlib<3.0.0,>=2.1.1->xpressplot) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from matplotlib<3.0.0,>=2.1.1->xpressplot) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from matplotlib<3.0.0,>=2.1.1->xpressplot) (2.8.1)
Requirement already satisfied: pytz in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from matplotlib<3.0.0,>=2.1.1->xpressplot) (2021.1)
Requirement already satisfied: six>=1.10 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from matplotlib<3.0.0,>=2.1.1->xpressplot) (1.15.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from matplotlib<3.0.0,>=2.1.1->xpressplot) (1.3.1)
Requirement already satisfied: retrying>=1.3.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from plotly->xpressplot) (1.3.3)
Requirement already satisfied: statsmodels>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from plotly_express->xpressplot) (0.12.2)
Requirement already satisfied: patsy>=0.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from plotly_express->xpressplot) (0.5.1)
Requirement already satisfied: joblib>=0.11 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from scikit-learn->xpressplot) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from scikit-learn->xpressplot) (2.1.0)
```

Now I enter python
```
arish@dhcp-10-29-251-173 ~ % python                          
Python 3.9.2 (v3.9.2:1a79785e3e, Feb 19 2021, 09:06:10) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

Importing xpressplot seems to fail
```
>>> import xpressplot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/xpressplot/__init__.py", line 24, in <module>
    from .fetch import *
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/xpressplot/fetch.py", line 30, in <module>
    from .normalize import clean_df
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/xpressplot/normalize.py", line 31, in <module>
    import matplotlib.pyplot as plt
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/pyplot.py", line 31, in <module>
    import matplotlib.colorbar
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/contour.py", line 22, in <module>
    import matplotlib.font_manager as font_manager
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/font_manager.py", line 60, in <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/ft2font.cpython-39-darwin.so, 2): Symbol not found: _FT_Done_Face
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/ft2font.cpython-39-darwin.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/ft2font.cpython-39-darwin.so
```
Have you experienced this problem before?
I think it might be an issue with freetype as the issue "Symbol not found:_FT_Done_Face" might indicate.

Best,
Arish

**Keep this to auto-ping a maintainer**
@j-berg

**Comment by j-berg** [comment]
Hi Arish,

Sorry you are running into this problem! It does look like it might be an issue with the M1 chip, but related to one of XPRESSplot's dependencies, Matplotlib. Could you try the solution discussed here: https://alexslobodnik.medium.com/apple-m1-matplotlib-python-and-jupyter-lab-551646b9a8cd

It looks like if you force install `libjpeg` using `brew` it might work
```
brew install libjpeg
```

This might grab a compatible version of the dependency. Then you can try reimporting XPRESSplot. Let me know if this works and then I can add this to the install. If not, we can keep trying to troubleshoot.

Thanks!

**Comment by arish-n-shah** [comment]
Maybe I am doing something wrong with brew? It is still throwing the same error.

listing everything installed via brew:
```
arish@dhcp-10-29-251-173 ~ % ls /opt/homebrew/bin 
brew		djpeg		jpegtran	libpng16-config	png-fix-itxt	rdjpgcom
cjpeg		freetype-config	libpng-config	pkg-config	pngfix		wrjpgcom
```

installing libjpeg:
```
arish@dhcp-10-29-251-173 ~ % brew install jpeg libjpeg
Warning: jpeg 9d is already installed and up-to-date.
To reinstall 9d, run:
  brew reinstall jpeg
```

confirming python version:
```
arish@dhcp-10-29-251-173 ~ % python --version
Python 3.9.2
```

importing xpressplot still fails on the same "Symbol not found: _FT_Done_Face" error: 
```
arish@dhcp-10-29-251-173 ~ % python
Python 3.9.2 (v3.9.2:1a79785e3e, Feb 19 2021, 09:06:10) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import xpressplot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/xpressplot/__init__.py", line 24, in <module>
    from .fetch import *
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/xpressplot/fetch.py", line 30, in <module>
    from .normalize import clean_df
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/xpressplot/normalize.py", line 31, in <module>
    import matplotlib.pyplot as plt
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/pyplot.py", line 31, in <module>
    import matplotlib.colorbar
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/contour.py", line 22, in <module>
    import matplotlib.font_manager as font_manager
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/font_manager.py", line 60, in <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/ft2font.cpython-39-darwin.so, 2): Symbol not found: _FT_Done_Face
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/ft2font.cpython-39-darwin.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/ft2font.cpython-39-darwin.so
>>> 
zsh: suspended  /usr/local/bin/python3
arish@dhcp-10-29-251-173 ~ % 
```

I am able to call the brew and brew-installed functions after adding /opt/homebrew/bin to my PATH, so I don't think that PATH is the problem.

**Comment by j-berg** [comment]
Hmm, maybe its not an M1 issues after all. Can you try the following:
```
conda create -n xpressplot -c bioconda xpressplot 
conda activate xpressplot
python
```
Maybe it is clashing with other dependencies so we can try installing in a stand-alone Conda env to debug

Then, within the Python interpreter, run:
```
import xpressplot
```

If that doesn't work, can you run the following in the Python interpreter and let me know the output?
```
import sys 
print(sys.platform)
print(sys.implementation)
```

**Comment by arish-n-shah** [comment]
That did the trick!

Creating a new environment for xpressplot seems to work:
```
conda create -n xpressplot -c bioconda xpressplot 
conda activate xpressplot
python
```

Followed by:
`>>>import xpressplot`
This no longer throws any errors.

**Comment by j-berg** [comment]
Awesome, that is great news! For the future then, I would recommend installing and running XPRESSpipe and/or XPRESSplot within a specific conda environment that you activate before use. I will go ahead and close this issue, but please feel free to re-open it or submit another issue if you come across anything else!
