### ISSUE TITLE
xpresspipe failure in urllib

### ISSUE THREAD

**Issue by arish-n-shah** [XPRESSyourself/XPRESSpipe#48]
When trying to use xpresspipe to align riboseq data, there seems to be a problem in urllib.
MacOS Big Sur 11.2
M1 Chip

I have an xpresspipe environment activated and it tests correctly:

```
(base) -bash-4.2$ conda activate xpresspipe
(xpresspipe) -bash-4.2$ xpresspipe test

You are using the current version of XPRESSpipe...
======================
User commands summary:
======================
XPRESSpipe version: 0.6.2
cmd: test
suppress_version_check: False
path: /home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/site-packages/xpresspipe/
log_loc: ./
experiment: test_2021_3_1_14h_27m_1s
log:  >> ./test_2021_3_1_14h_27m_1s.log 2>&1
log_file: ./test_2021_3_1_14h_27m_1s.log
=====================
End commands summary
=====================

Installation successful
(xpresspipe) -bash-4.2$ 
```

Now, I qsub my Alignment.sh file:
```
> #!/bin/bash
> #SBATCH -N 1
> #SBATCH -n 4
> #SBATCH --output=Alignments.out
> #SBATCH --job-name="RiboAlign"
> source /home/arish/.bashrc
> conda activate xpresspipe
> 
> echo "Aligning"
> echo ============================================================
> 
> xpresspipe riboseq -i processed -o riboseq_output -e LSU_IP --cdna_fasta riboseq_reference/Danio_rerio.GRCz11.cdna.all.fa -r riboseq_reference/genome_fasta -g riboseq_reference/GRCz11.Lawson.v4.3.2_CT.gtf --method RPM --sjdbOverhang 49 -m 8

> 
> echo "Complete"
> echo ============================================================
> 
> echo "End time = "
> date
```

"processed" is a folder which contains split, UMI-deduplicated-and-removed, adapter-removed, footprint-seq and RNA-seq fastq files
"riboseq_output" is an empty folder in the current dir
"LSU_IP" is just the name of the experiment
"Danio_rerio.GRCz11.cdna.all.fa" is the all cDNA file downloaded from Ensembl
"riboseq_reference/genome_fasta" is a folder with 25 chromosome.fa files
"riboseq_reference/..._CT.gtf" is the gtf file created after using curateReference

The pipeline throws this error:
```
Traceback (most recent call last):
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/http/client.py", line 1384, in connect
    super().connect()
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arish/packages/miniconda3/envs/xpresspipe/bin/xpresspipe", line 8, in <module>
    sys.exit(main())
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/site-packages/xpresspipe/__main__.py", line 130, in main
    __version__)
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/site-packages/xpresspipe/arguments.py", line 2239, in get_arguments
    args_dict = check_inputs(args_dict)
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/site-packages/xpresspipe/arguments.py", line 371, in check_inputs
    webpage = urlopen(req).read()
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/arish/packages/miniconda3/envs/xpresspipe/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

```

**Keep this to auto-ping a maintainer**
@j-berg

**Comment by j-berg** [comment]
A couple questions:
- Just to orient myself, are you running your script on SLURM? Or is `qsub` SLURM-compatible? Is `qsub` executed directly on your computer, or do you SSH into an HPC cluster first?
- The point in the code where this error is arising is run for both `xpresspipe test` and xpresspipe riboseq`, so I am wondering if there was an internet connection issue? Have you tried rerunning the script to see if the connection issue resolves itself?
- Could you also change your conda activation line in your `alignment.sh` script to `source activate xpresspipe` and see if that does anything?
